services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./zDB/postgres:/var/lib/postgresql/data
      - ./zDB/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=farmstand_tracker
