services:
  fs_database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./zDB/postgres:/var/lib/postgresql/data
      - ./zDB/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=farmer
      - POSTGRES_DB=farmstand_tracker

  farmstand:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "8080:8080"
    links:
      - fs_database
    environment:
      FS_DB_HOST: "fs_database"