### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

### GET all
GET http://0.0.0.0:8080/farmstand


### GET by name
GET http://0.0.0.0:8080/farmstand/byName/mint


### POST - Create a farmstand
POST http://0.0.0.0:8080/farmstand
Content-Type: application/json

{ "name" : "beans", "initDate": "2012-04-23" }


### POST - Shutdown a farmstand - this should be successful the first time it is run after starting the app
POST http://0.0.0.0:8080/farmstand/Strawberries
Content-Type: application/json

{ "shutdownDate": "2012-04-25" }

### POST - Shutdown a farmstand - this should be fail (404)
POST http://0.0.0.0:8080/farmstand/onions
Content-Type: application/json

{ "shutdownDate": "2012-04-25" }

### DELETE
DELETE http://0.0.0.0:8080/farmstand/mint