### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### GET active farmstands
GET http://0.0.0.0:8080/farmstand

### GET all farmstands
GET http://0.0.0.0:8080/farmstand/all

### GET inactive farmstands
GET http://0.0.0.0:8080/farmstand/shutdown

### GET by name - mint
GET http://0.0.0.0:8080/farmstand/mint


### GET by name - beans
GET http://0.0.0.0:8080/farmstand/beans


### POST - Create a farmstand - beans
POST http://0.0.0.0:8080/farmstand
Content-Type: application/json

{ "name" : "beans", "initDate": "2012-04-23" }


### POST - Create a farmstand - mint
POST http://0.0.0.0:8080/farmstand
Content-Type: application/json

{ "name" : "mint", "initDate": "2012-04-11" }


### POST - Shutdown a farmstand - beans
POST http://0.0.0.0:8080/farmstand/beans
Content-Type: application/json

{ "shutdownDate": "2012-04-25" }

### POST - Shutdown a farmstand - this should be successful the first time it is run after starting the app
POST http://0.0.0.0:8080/farmstand/Strawberries
Content-Type: application/json

{ "shutdownDate": "2012-04-25" }

### POST - Shutdown a farmstand - this should be fail (404)
POST http://0.0.0.0:8080/farmstand/onions
Content-Type: application/json

{ "shutdownDate": "2012-04-25" }

### DELETE
DELETE http://0.0.0.0:8080/farmstand/beans


### POST - Add Measurement
POST http://0.0.0.0:8080/1/measurement
Content-Type: application/json

{
  "date": "2024-10-26",
  "context": "TAP_WATER",
  "ph": 5.70,
  "temp": {
    "value": 19,
    "metric": "CELCIUS"
  },
  "ec": 2.4,
  "notes": "this is just the beginning"
}

### GET all measurements for a farmstand
GET http://0.0.0.0:8080/1/measurement
