name: Farmstand Info Service
run-name: Main Build

on: [push]

jobs:
  Build-and-Package:
    name: Build and Package the Farmstand Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Run the tests
        run: ./gradlew clean integrationTest

      - name: Build the Docker image
        run: docker build . --file ./src/main/docker/Dockerfile --tag "farmstand-info-service:${SHORT_SHA}"
